### ISSUE TITLE
Nello script manca R1 

### ISSUE THREAD

**Issue by fiveten59** [knap-net/Script-VDR#1]
```
###################################
#   Rimozione Repository Locale   #
###################################
```

R1)
    clear
    echo "         Rimozione Directory Repository Locale "; sleep 4 
    echo "        ---------------------------------------"
    echo "        Che cosa vuoi rimuovere dai repository " 
    echo "        ---------------------------------------"
    echo "        [a]  Sorgenti di VDR                   "
    echo "        [b]  Sorgenti di DVBAPI                "
    echo "        [c]  Sorgenti di SC                    "
    echo "        [d]  Tutto il contenuto                "
    echo "        [e]  Skip                              "
    echo "                                               "
    echo "        ---------------------------------------"
    echo -n "        Scegli  [a-e]:      "
    read yourch
    case $yourch in
    a) rm /home/`logname`/sifinstallrepo/vdr-2.2.0.tar.bz2;;
    b) rm -r /home/`logname`/sifinstallrepo/vdr-plugin-dvbapi;;
    c) rm -r /home/`logname`/sifinstallrepo/sc;;
    d) rm -r /home/`logname`/sifinstallrepo;;
    e) ;;
    esac
    echo "                    Premere il tasto [Invio] per continuare. . .               "; read enterKey;;

**Comment by knapnet** [comment]
ok
