### ISSUE TITLE
Piccola patch 

### ISSUE THREAD

**Issue by fiveten59** [knap-net/Script-VDR#5]
Io farei questa piccola patch ... per coerenza di argomenti w_scan e getchannels ora al punto 13 li metterei nella sezione della creazione liste. Ho poi modificato la sezione old di kingofsat aggiungento anche un x2 
Se questa la lasci così come l'ho fatta (channels13.conf e channels19.conf) ti ringrazio

--- installer.old   2015-06-08 09:04:10.080351545 +0200
+++ installer   2015-06-08 11:46:07.400194000 +0200
@@ -2500,28 +2500,6 @@
 esac

 ##################################################
-#       Caricamento W_scan e Getchannels         #
-##################################################
-clear
-echo "               **\* Caricamento Getchannels ***"; sleep 3
-if [ -f /$SRC/getchannels/getchannels.py ];
-  then  echo "Getchannels $Remind3"
  -else
  -cp -r /home/`logname`/sifinstallrepo/getchannels.tar.gz /$SRC;
  -cd /$SRC && tar -zxvf getchannels.tar.gz && rm -r getchannels.tar.gz;
  -fi
  -clear
  -echo "               **\* Caricamento W_scan ***"; sleep 3
  -cd /usr/local/src; 
  -# wget http://wirbel.htpc-forum.de/w_scan/w_scan-20141122.tar.bz2;
  -if [ -f /$SRC/w_scan/Makefile ];
-  then  echo "W_scan $Remind3"
  -else
  -cp /home/`logname`/sifinstallrepo/w_scan-20141122.tar.bz2 $SRC/; 
  -tar xivf w_scan-20141122.tar.bz2; mv w_scan-20141122 w_scan; rm -r w_scan-20141122.tar.bz2; 
  -cd w_scan; ./configure; make; make install;
  -fi
  -##################################################
  #       Caricamento Sif Appswitcher (prova)      #
  ##################################################
  #cd /usr/bin; rm -r menuorg-appswitcher, rm -r kodi.sh;
  @@ -3839,8 +3817,29 @@
  17)                                       #########################################
                                           #         Creazione lista canali        #
                                           #########################################
  -
  -
  +##################################################
  +#       Caricamento W_scan e Getchannels         #
  +##################################################
  +clear
  +echo "               **\* Caricamento Getchannels ***"; sleep 3
  +if [ -f /$SRC/getchannels/getchannels.py ];
-  then  echo "Getchannels $Remind3"
  +else
  +cp -r /home/`logname`/sifinstallrepo/getchannels.tar.gz /$SRC;
  +cd /$SRC && tar -zxvf getchannels.tar.gz && rm -r getchannels.tar.gz;
  +fi
  +clear
  +echo "               **\* Caricamento W_scan ***"; sleep 3
  +cd /usr/local/src; 
  +# wget http://wirbel.htpc-forum.de/w_scan/w_scan-20141122.tar.bz2;
  +if [ -f /$SRC/w_scan/Makefile ];
-  then  echo "W_scan $Remind3"
  +else
  +cp /home/`logname`/sifinstallrepo/w_scan-20141122.tar.bz2 $SRC/; 
  +tar xivf w_scan-20141122.tar.bz2; mv w_scan-20141122 w_scan; rm -r w_scan-20141122.tar.bz2; 
  +cd w_scan; ./configure; make; make install;
  +fi
  +##############################################################################################################################
   clear  
   dialog --title "   *\* Creazione && Aggiornamento Settings - Diversi Metodi *\*   " --infobox "
  --------------------------------------------------------------
  @@ -3910,12 +3909,12 @@
       [u]    Vhannibal Hot Bird + DTT Torino  ............
       [v]    Vhannibal Dual + DTT Torino  ................  ****\*  Sezione Getchannels  *****
       [x]    Vhannibal Motor + DTT Torino  ...............  [x1]    Creazione Settings 13.0E - Download da Kingofsat (old)
-        [y]    Vhannibal Motor + DTT Forli'  ...............
- ```
     [y]    Vhannibal Motor + DTT Forli'  ...............  [x2]    Creazione Settings 19.2E - Download da Kingofsat (old)
  
   [z]    Skip 
  ```
  
  -------------------------------------------------------------------------------------------------------------------------------" 0 0
-    echo -n "        Scegli  Vhannibal [a-y]   Morpheus [a1-x1]:        "
-    echo -n "        Scegli  Vhannibal [a-y]   Morpheus [a1-x2]:        "
   read yourch
   case $yourch in

@@ -4432,8 +4431,13 @@
     python getchannels.py --useconfig getchannels.conf --list 13.0E --output $SRC/setting/getchannels/output/channels.conf;
     cp $SRC/setting/getchannels/output/channels.conf /etc/vdr/;;
-    x1) cd $SRC/setting/getchannels && python getchannels.py --useconfig getchannels.conf --list 13.0E --output $SRC/getchannels/output/channels.conf;
-    sleep  4; cp $SRC/setting/getchannels/output/channels.conf /etc/vdr/;;
-    ##### Sezione Kingofsat (old) #####
  +
-    x1) cd $SRC/setting/getchannels && python getchannels.py --useconfig getchannels.conf --list 13.0E --output $SRC/getchannels/output/channels13.conf;
-    sleep  4; cp $SRC/setting/getchannels/output/channels13.conf /etc/vdr/;;
  +
-    x2) cd $SRC/setting/getchannels && python getchannels.py --useconfig getchannels.conf --list 19.2E --output $SRC/getchannels/output/channels19.conf;
-    sleep  4; cp $SRC/setting/getchannels/output/channels19.conf /etc/vdr/;;
  
   z) ;;
   esac

**Comment by knapnet** [comment]
Questa patch puoi applicarla tu stesso ... la lasciamo cosi in x2 .... non da fastidio ...

Ho contattato Armando Basile , Mona66, Morpheus883 e Grazymax ....

In Pratica Ho modificato lo Script-VDR al Punto 17 e Aggiunto del nuovo codice, Creato il sotto-menu ... ecc....

Al punto 17 come gia ti avevo accennato con Lamedb2vdr.sh si convertono i Settings Enigma2 di (f)-Vhannibal e (g)-Morpheus ....

Poi in (b~e) sezione W_Scan ....

Novita' introdotta al Punto 17 e Sezione (a)-Lamedb2vdr.sh (Mod. By Grazymax) - Getchannels
Che modificheremo per ottenere totale funzionalita' ...

Ho informato Mona66 e Armando sul funzionamento e non in alcuni casi .... in pratica:
Lamedb2vdr.sh (Modificato) converte Settings Enigma 2 in file di testo ...(getchannel.conf)

Del tipo:
:TV - Top Italia
Rai 1 HD;Rai

Poi Getchannel legge il file creato (getchannel.conf) ... 
Scarica i dati da kingofsat e crea il channel.conf .....

Qui sono sorti diversi problemi nel fare' cio' ....

1) Getchanel in opzione "--list" non funziona su diversi satelliti (es: --list 7.0E, 13.0E, 19.2E, 28.0E) da errore ...

2) Getchanel crea un output parzialmente corretto solo in 13.0E ....
In altri Satelliti No ... oppure importa qualche canale su altri Satelliti ...

3) Getchanel non importa i Parametri da Kingofsat ... 
Se il =>>  'Nome_Canale;Provider' <<=  risulta diverso ....

Esempio:
Cosi non importa Nulla:
EXOTICA TV;Telefonica Spain

Cosi Importa parametri:
EXOTICA TV;TelefonicaSpai

Si possono trovare molteplici soluzioni per effettuare il lavoro nel migliore dei modi ...

1) si puo' ottenere un output diverso da Lamedb2vdr.sh e permettere ad un nuovo Script di Armando di Aggiungere Pid Audio/Video mancanti ....

2) si puo' creare un nuovo modo tramite Getchannel di importare lista canali e dati completi da kingofsat con la selezione di diversi satelliti ...

3) si possono risolvere i problemi sopra descritti .... e tutto funziona ...

Armando a ricevuto la mia email e mi ha detto che fara' tutto il possibile per rendere questa modifica fattibile .... Gli serve un po' di tempo ....

**Comment by knapnet** [comment]
Fiveten_59 per la patch non posso applicarla l'output e errato qui usando i messaggi 'issue'

Se vuoi che la devo aggiungere scrivi la patch in 'Revision-Diff' ... mantiene il format usando estensione .patch o .diff ...

**Comment by fiveten59** [comment]
Hai ragione ... modificata e testata ora ...
Sto provando il nuovo plugin mpv ora in fase alfa o beta
qundo più stabile lo caricherò
