### ISSUE TITLE
problem with the files in sifinstallrepo

### ISSUE THREAD

**Issue by killahop** [knap-net/Script-VDR#9]
Vdr installing the script I get the error checking I noticed that the vdr-patches.2.2.0.tar.gz file was not present on Dropbox in https://www.dropbox.com/s/0fpr5q0jf85haen/vdr-patches.2.2.0.tar.gz

Installando la vdr dallo script ho ricevuto degli errori compilando VDR ed ho notato che al link su dropbox non era piu presente questo file vdr-patches.2.2.0.tar.gz

**Comment by fiveten59** [comment]
This is the right link

https://www.dropbox.com/s/s43vzyjc61rxdnt/vdr-patches.2.2.0.tar.gz
